export const data = [
  {
    name: 'Apple',
    category: 'Fruit',
    price: '$2.00',
    quantity: '100gr',
    image: require('./apple-01.jpg'),
  },
  {
    name: 'Banana',
    category: 'Fruit',
    price: '$3.00',
    quantity: '100gr',
    image: require('./bananas-01.jpg'),
  },
  {
    name: 'Spinach',
    category: 'Vegetable',
    price: '$1.00',
    quantity: '100gr',
    image: require('./spinach.png'),
  },

  {
    name: 'Tomato',
    category: 'Vegetable',
    price: '$2.00',
    quantity: '100gr',
    image: require('./tomato.jpg'),
  },
  {
    name: 'Beef',
    category: 'Meat',
    price: '$40.00',
    quantity: '1 kg',
    image: require('./meat.jpg'),
  },
  {
    name: 'Apple',
    category: 'Fruit',
    price: '$2.00',
    quantity: '100gr',
    image: require('./apple-01.jpg'),
  },
  {
    name: 'Banana',
    category: 'Fruit',
    price: '$3.00',
    quantity: '100gr',
    image: require('./bananas-01.jpg'),
  },
  {
    name: 'Spinach',
    category: 'Vegetable',
    price: '$1.00',
    quantity: '100gr',
    image: require('./spinach.png'),
  },

  {
    name: 'Tomato',
    category: 'Vegetable',
    price: '$2.00',
    quantity: '100gr',
    image: require('./tomato.jpg'),
  },
  {
    name: 'Beef',
    category: 'Meat',
    price: '$40.00',
    quantity: '1 kg',
    image: require('./meat.jpg'),
  },
  {
    name: 'Apple',
    category: 'Fruit',
    price: '$2.00',
    quantity: '100gr',
    image: require('./apple-01.jpg'),
  },
  {
    name: 'Banana',
    category: 'Fruit',
    price: '$3.00',
    quantity: '100gr',
    image: require('./bananas-01.jpg'),
  },
  {
    name: 'Spinach',
    category: 'Vegetable',
    price: '$1.00',
    quantity: '100gr',
    image: require('./spinach.png'),
  },

  {
    name: 'Tomato',
    category: 'Vegetable',
    price: '$2.00',
    quantity: '100gr',
    image: require('./tomato.jpg'),
  },
  {
    name: 'Beef',
    category: 'Meat',
    price: '$40.00',
    quantity: '1 kg',
    image: require('./meat.jpg'),
  },
];
